### ISSUE TITLE
Raw URL for playlists and recommendations

### ISSUE THREAD

**Issue by Tony-MF** [cloudinary/cloudinary-video-player#250]
Hi guys,

I saw you added support for raw URLs. Is it possible to use it for Playlists and/or recommendations too? I was not able to figure it out. If so, could you show me an example? If not, are you planning to add it in the future?

Thanks

**Comment by leptians** [comment]
Hi Tony, 

Can you elaborate more regarding what you are trying to achieve? When you mentioned about raw URLs, Is it Cloudinary URL with resource_type: raw, or do you mean it's non-Cloudinary Video URL.

If you can share an example of your code for me to reproduce it on JSFiddle or something similar, I'll be happy to take a look at it.

Regards,
Erwin Lukas

**Comment by Tony-MF** [comment]
Hello Erwin,

I meant non-Cloudinary Video URL. Sure, here is an example -
https://jsfiddle.net/kntayh39/.

Basically, I'm trying to use your player (and its recommendations feature)
for videos stored in our storage instead of Cloudinary.

Thanks,

Tony

**Comment by michalkcloudinay** [comment]
Hi Tony, Thanks for sharing an example. 
The `sources` in the `player.playlist` function can be passed in two ways: 
1. Object- which is available only for Cloudinary URLs since it includes a public_id. 
2. URL as a String- available for non Cloudinary sources as well. 
For example: 
```
var source1="https://www.myvideo1.mp4"
var source2="https://www.myvideo2.mp4"

player.playlist([source1,source2], {
}); 
```

Please note that since you can't pass an Object for non Cloudinary URLs, you cant use recommendations in this case. 

Please let us know if this works for you.

Regards,
Michal

**Comment by Tony-MF** [comment]
Amazing, thank you. In case #2, I can't add a thumbnail, right?

Thanks,

Tony

**Comment by michalkcloudinay** [comment]
You are correct, can't include a thumbnail as well in this case.

**Comment by Tony-MF** [comment]
Ok, thanks for the clarification.

Tony

**Comment by michalkcloudinay** [comment]
You are welcome. Let us know if you have any further questions.
